import React, {FormEvent, useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {ArrowLeft, ArrowRight, Check, Clock3, MapPin, Menu as MenuIcon, Minus, Phone, Plus, Search, ShoppingBag, Trash2, X} from 'lucide-react';
import './styles.css';

type MenuItem={name:string;price:string;desc:string;tag:string;category:string;image:string;sizes?:string[]};
type CartItem={id:string;name:string;size:string;toppings:string[];instructions:string};
type Day={day:string;open?:string;close?:string};

const pizza='https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&w=1000&q=85';
export const restaurantConfig={
 name:"Mama Mia's Pizzeria",established:1980,timezone:'America/New_York',phone:'814-790-5868',orderingUrl:import.meta.env.VITE_ORDERING_URL||'',
 address:{street:'1529 W 38th St',city:'Erie',state:'PA',zip:'16508'},
 features:{dineInEnabled:false,carryoutEnabled:true,deliveryEnabled:true,onlineOrderingEnabled:false,cateringEnabled:false},
 hours:[{day:'Monday'},{day:'Tuesday'},{day:'Wednesday',open:'4 PM',close:'8 PM'},{day:'Thursday',open:'4 PM',close:'8 PM'},{day:'Friday',open:'3 PM',close:'9 PM'},{day:'Saturday',open:'3 PM',close:'9 PM'},{day:'Sunday',open:'3 PM',close:'7 PM'}] as Day[],
 menu:[
  {name:'Cheese Pizza',price:'$8.99 / $10.55',desc:'Fresh dough, house-made tomato sauce, and mozzarella.',tag:'THE ORIGINAL',category:'Pizza',sizes:['12” Small — $8.99','14” Large — $10.55'],image:pizza},
  {name:'Meatlovers',price:'$16.85',desc:'Mozzarella, pepperoni, ham, meatballs, sausage, and bacon.',tag:'SPECIALTY',category:'Specialty Pizza',sizes:['14” Large — $16.85'],image:'https://images.unsplash.com/photo-1594007654729-407eedc4be65?auto=format&fit=crop&w=1000&q=85'},
  {name:'Italian White',price:'$12.05 / $14.85',desc:'Olive oil, ricotta, garlic, mozzarella, mushrooms, onions, sweet peppers, oregano, and basil.',tag:'SPECIALTY',category:'Specialty Pizza',sizes:['12” Small — $12.05','14” Large — $14.85'],image:'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&w=1000&q=85'},
  {name:'Traditional Wings',price:'$12.99',desc:'Sold by the pound and includes house-made ranch. Choose your sauce.',tag:'WINGS',category:'Wings',sizes:['One pound — $12.99'],image:'https://images.unsplash.com/photo-1527477396000-e27163b481c2?auto=format&fit=crop&w=1000&q=85'},
  {name:'Boneless Wings',price:'$10.29',desc:'8–10 pieces, tossed in sauce or served naked with dipping sauce.',tag:'WINGS',category:'Wings',sizes:['8–10 pieces — $10.29'],image:'https://images.unsplash.com/photo-1608039755401-742074f0548d?auto=format&fit=crop&w=1000&q=85'},
  {name:'Stromboli',price:'$11.69 / $14.45',desc:'Mozzarella, pepperoni, sausage, mushrooms, onions, sweet peppers, and pizza sauce.',tag:'OVEN BAKED',category:'Strombolis',sizes:['Small — $11.69','Large — $14.45'],image:'https://images.unsplash.com/photo-1625398407796-82650a8c135f?auto=format&fit=crop&w=1000&q=85'},
  {name:'Chicken Parmigiana Sub',price:'$7.89',desc:'Marinara, chicken tenders, parmesan, and mozzarella on a toasted 10-inch sub.',tag:'SUBS',category:'Subs',sizes:['10” — $7.89'],image:'https://images.unsplash.com/photo-1550507992-eb63ffee0847?auto=format&fit=crop&w=1000&q=85'},
  {name:'Antipasto Salad',price:'$5.69 / $10.25 / $11.05',desc:'Mixed greens, ham, salami, provolone, pepperoni, chickpeas, olives, tomatoes, and pepperoncini.',tag:'SALADS',category:'Salads',sizes:['Mini — $5.69','Small — $10.25','Large — $11.05'],image:'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=1000&q=85'},
  {name:'Breadsticks',price:'$4.99',desc:'Made with our fresh dough. Add mozzarella or marinara.',tag:'STARTERS',category:'Sides',sizes:['Order — $4.99'],image:'https://images.unsplash.com/photo-1573140401552-3fab0b24306f?auto=format&fit=crop&w=1000&q=85'}
 ] as MenuItem[]
};

const directions=`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(`${restaurantConfig.name} ${restaurantConfig.address.street} ${restaurantConfig.address.city} ${restaurantConfig.address.state} ${restaurantConfig.address.zip}`)}`;
const callHref=`tel:+1${restaurantConfig.phone.replace(/\D/g,'')}`;
function getStatus(){const now=new Date(new Date().toLocaleString('en-US',{timeZone:restaurantConfig.timezone}));const index=now.getDay()===0?6:now.getDay()-1;const today=restaurantConfig.hours[index];const parse=(v:string)=>{const [n,a]=v.split(' ');let h=Number(n.split(':')[0]);const m=Number(n.split(':')[1]||0);if(a==='PM'&&h!==12)h+=12;if(a==='AM'&&h===12)h=0;return h*60+m};if(!today.open||!today.close)return{open:false,label:'CLOSED TODAY'};const minute=now.getHours()*60+now.getMinutes(),open=parse(today.open),close=parse(today.close);return{open:minute>=open&&minute<close,label:minute<open?`OPENS TODAY AT ${today.open}`:minute<close?`OPEN UNTIL ${today.close}`:'CLOSED NOW'}}
function goOrder(){window.location.href=restaurantConfig.orderingUrl||'/order'}

function Header({count}:{count:number}){const[open,setOpen]=useState(false);return <header><a className="brand" href="/home"><span>MAMA MIA'S</span><small>PIZZERIA · ERIE, PA</small></a><nav className={open?'open':''}><a href="/menu">Menu</a><a href="/our-story">Our Story</a><a href="/locations">Locations</a><a href="/contact">Contact</a><a className="cart-link" href="/order"><ShoppingBag size={16}/> Cart {count>0&&<b>{count}</b>}</a><button className="btn btn-red" onClick={goOrder}>ORDER ONLINE <ArrowRight size={16}/></button></nav><button className="menu-btn" aria-label="Toggle navigation" aria-expanded={open} onClick={()=>setOpen(!open)}>{open?<X/>:<MenuIcon/>}</button></header>}
function Footer(){return <><footer><a className="brand" href="/home"><span>MAMA MIA'S</span><small>PIZZERIA · ERIE, PA</small></a><div><b>{restaurantConfig.address.street} · Erie, PA 16508</b><a href={callHref}>{restaurantConfig.phone}</a><span>Serving Erie since 1980.</span></div><div className="footer-links"><a href="/menu">Menu</a><a href="/our-story">Our Story</a><a href="/locations">Locations</a><a href="/contact">Contact</a></div></footer><div className="mobile-bar"><a href="/menu">MENU</a><button onClick={goOrder}>ORDER ONLINE</button><a href={callHref}>CALL</a></div></>}
function PageIntro({eyebrow,title,children}:{eyebrow:string;title:string;children:React.ReactNode}){return <section className="page-intro"><div className="eyebrow">{eyebrow}</div><h1>{title}</h1><p>{children}</p></section>}

function Home(){const s=getStatus();return <main><section className="hero"><div className="hero-copy"><div className="eyebrow"><span className="dot"/> ERIE'S NEIGHBORHOOD PIZZA</div><h1>Pizza made the way Erie remembers it.</h1><p>Fresh dough, homemade sauce, and a whole lot of local history. Mama Mia's has been bringing people together since 1980.</p><div className="actions"><button className="btn btn-red" onClick={goOrder}>ORDER ONLINE <ArrowRight size={17}/></button><a className="btn btn-outline" href="/menu">VIEW MENU</a></div><div className="hero-meta"><div><MapPin size={16}/><span>{restaurantConfig.address.street}<br/><b>Erie, PA 16508</b></span></div><div className={s.open?'open-status':''}><Clock3 size={16}/><span><b>{s.label}</b><small>Hours vary by day</small></span></div></div></div><div className="hero-art"><div className="stamp">EST.<strong>1980</strong></div><div className="pizza"><div className="pep p1"/><div className="pep p2"/><div className="pep p3"/><div className="pep p4"/><div className="pep p5"/></div><div className="art-caption">THE ERIE<br/>ORIGINAL</div></div></section><section className="quick"><button onClick={goOrder}><span>01</span><b>Order online</b><ArrowRight/></button><a href="/menu"><span>02</span><b>Browse menu</b><ArrowRight/></a><a href={callHref}><span>03</span><b>Call to order</b><Phone/></a><a href={directions} target="_blank" rel="noreferrer"><span>04</span><b>Get directions</b><MapPin/></a></section><section className="values section"><div><div className="eyebrow">WHY MAMA MIA'S</div><h2>The good stuff is simple.</h2></div><div className="value-grid"><div><strong>01</strong><h3>Fresh dough</h3><p>Made for the day, never an afterthought.</p></div><div><strong>02</strong><h3>Homemade sauce</h3><p>The red sauce that makes pizza feel like home.</p></div><div><strong>03</strong><h3>Erie proud</h3><p>Four decades in the neighborhood and counting.</p></div></div></section><section className="order-note"><div><div className="eyebrow">DINNER, HANDLED</div><h2>What's for dinner?</h2><p>Browse the menu, customize your favorites, then call to confirm your order while online checkout is being connected.</p></div><a className="btn btn-red" href="/menu">START AN ORDER <ArrowRight size={17}/></a></section></main>}

function MenuPage({add}:{add:(item:MenuItem)=>void}){const[cat,setCat]=useState('All'),[search,setSearch]=useState('');const cats=['All',...Array.from(new Set(restaurantConfig.menu.map(x=>x.category)))];const items=useMemo(()=>restaurantConfig.menu.filter(x=>(cat==='All'||x.category===cat)&&`${x.name} ${x.desc}`.toLowerCase().includes(search.toLowerCase())),[cat,search]);return <main><PageIntro eyebrow="THE MENU" title="Made for Erie appetites.">Current menu and prices sourced from Mama Mia's existing public menu. Availability can change—call the shop with questions.</PageIntro><section className="section menu-section"><div className="menu-tools"><div className="cats" role="tablist" aria-label="Menu categories">{cats.map(x=><button role="tab" aria-selected={cat===x} className={cat===x?'active':''} onClick={()=>setCat(x)} key={x}>{x}</button>)}</div><label className="search"><Search size={16}/><span className="sr-only">Search menu</span><input placeholder="Search menu" value={search} onChange={e=>setSearch(e.target.value)}/></label></div>{items.length?<div className="food-grid">{items.map((x,i)=><article className="food-card" key={x.name}><div className="food-image"><img src={x.image} alt="" loading={i<3?'eager':'lazy'}/><span>{x.tag}</span></div><div className="food-info"><div className="food-title"><h3>{x.name}</h3><b>{x.price}</b></div><p>{x.desc}</p><button className="customize-link" onClick={()=>add(x)}>Customize <ArrowRight size={14}/></button></div></article>)}</div>:<div className="empty-state"><h2>No matches</h2><p>Try another search or category.</p></div>}<p className="menu-note">Prices and availability should be reconfirmed before the business changes ownership.</p></section></main>}
function StoryPage(){return <main><PageIntro eyebrow="OUR STORY" title="Serving Erie since 1980.">Same Erie tradition. Fresh new chapter.</PageIntro><section className="story section"><div className="story-image"><div className="photo-label">ERIE, PA · EST. 1980</div></div><div className="story-copy"><div className="eyebrow">BUILT HERE</div><h2>Four decades of Erie pizza.</h2><p>Mama Mia's began serving Erie in 1980. After a plaza fire affected the former Peach Street location on May 14, 2019, the pizzeria reopened at 1529 W 38th Street on November 7, 2019.</p><p>Today, the fresh dough, homemade sauces, and house-made dressings continue at the West 38th Street shop.</p><a className="text-link" href="/locations">Visit the Erie location <ArrowRight size={16}/></a></div></section></main>}
function LocationsPage(){return <main><PageIntro eyebrow="LOCATIONS" title="Find your Mama Mia's.">The original Erie shop is open now. This location system is ready to grow with future Mama Mia's neighborhoods.</PageIntro><section className="visit section"><div><div className="eyebrow">ERIE · 38TH STREET</div><h2>The hometown location.</h2><p>Carryout and delivery are currently available. The dining room is currently closed.</p><div className="address"><MapPin/><span><b>{restaurantConfig.name}</b><br/>{restaurantConfig.address.street}<br/>Erie, PA 16508<br/><a href={callHref}>{restaurantConfig.phone}</a></span></div><div className="actions"><a className="btn btn-cream" href={directions} target="_blank" rel="noreferrer">GET DIRECTIONS</a><a className="btn btn-outline light" href={callHref}>CALL</a></div></div><Hours/></section><section className="franchise section"><div className="eyebrow">LOOKING AHEAD</div><h2>Bring Mama Mia's to your neighborhood.</h2><p>Franchise information is being developed as the brand enters its next chapter. Future locations will appear here.</p><a className="btn btn-dark" href="/contact">ASK ABOUT FRANCHISING <ArrowRight size={16}/></a></section></main>}
function Hours(){return <div className="hours"><h3>Hours</h3>{restaurantConfig.hours.map(x=><div key={x.day}><span>{x.day}</span><b>{x.open?`${x.open} – ${x.close}`:'Closed'}</b></div>)}</div>}
function ContactPage(){const[sent,setSent]=useState(false);function submit(e:FormEvent){e.preventDefault();setSent(true)}return <main><PageIntro eyebrow="CONTACT" title="Talk to the shop.">For orders and same-day questions, calling is always fastest.</PageIntro><section className="contact section"><div><h2>We’re here.</h2><p><a className="contact-line" href={callHref}><Phone/> {restaurantConfig.phone}</a></p><p><a className="contact-line" href={directions} target="_blank" rel="noreferrer"><MapPin/> {restaurantConfig.address.street}, Erie, PA 16508</a></p><p>Carryout and delivery are available. Dine-in is currently closed.</p></div>{sent?<div className="form-state"><Check/><h3>Your note is saved on this screen.</h3><p>Email delivery is not connected yet. Please call {restaurantConfig.phone} to reach the shop.</p><button className="btn btn-outline" onClick={()=>setSent(false)}>WRITE ANOTHER NOTE</button></div>:<form onSubmit={submit}><label>Name<input placeholder="Your name" required/></label><label>Email<input type="email" placeholder="you@example.com" required/></label><label>Phone <small>optional</small><input type="tel" placeholder="(814) 555-0123"/></label><label>Message<textarea placeholder="How can we help?" required/></label><button className="btn btn-dark">REVIEW MESSAGE <ArrowRight size={16}/></button><small>This preview does not transmit messages yet.</small></form>}</section></main>}
function OrderPage({cart,remove}:{cart:CartItem[];remove:(id:string)=>void}){return <main><PageIntro eyebrow="YOUR ORDER" title={cart.length?'Ready when you are.':'Start with the menu.'}>{cart.length?'Review your customized items below. Online payment is not connected during this private preview.':'Customize menu items and they’ll appear here.'}</PageIntro><section className="cart-page section">{cart.length?<><div className="cart-list">{cart.map(x=><article key={x.id}><div><h3>{x.name}</h3><p>{x.size}</p>{x.toppings.length>0&&<p>Extras: {x.toppings.join(', ')}</p>}{x.instructions&&<p>Note: {x.instructions}</p>}</div><button aria-label={`Remove ${x.name}`} onClick={()=>remove(x.id)}><Trash2/></button></article>)}</div><div className="cart-actions"><a className="btn btn-red" href={callHref}>CALL TO PLACE ORDER <Phone size={16}/></a><a className="btn btn-outline" href="/menu">ADD MORE ITEMS</a><p>Have this screen ready when you call. Final pricing and availability are confirmed by the shop.</p></div></>:<div className="empty-state"><ShoppingBag/><h2>Your cart is empty.</h2><a className="btn btn-red" href="/menu">VIEW MENU <ArrowRight size={16}/></a></div>}</section></main>}
function NotFound(){return <main className="not-found"><div className="eyebrow">404 · WRONG TURN</div><h1>This slice went missing.</h1><p>The page you’re looking for isn’t on the menu.</p><a className="btn btn-red" href="/home"><ArrowLeft size={16}/> BACK HOME</a></main>}

function Customizer({item,onClose,onAdd}:{item:MenuItem;onClose:()=>void;onAdd:(x:CartItem)=>void}){const[size,setSize]=useState(item.sizes?.[0]||'Regular'),[toppings,setToppings]=useState<string[]>([]),[notes,setNotes]=useState('');const extras=['Extra cheese','Pepperoni','Mushrooms','Onions','Sweet peppers','Banana peppers'];const toggle=(x:string)=>setToppings(v=>v.includes(x)?v.filter(y=>y!==x):[...v,x]);return <div className="customizer" role="dialog" aria-modal="true" aria-labelledby="customizer-title" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><div className="customizer-panel"><button className="close-customizer" onClick={onClose} aria-label="Close"><X/></button><div className="eyebrow">MAKE IT YOURS</div><h2 id="customizer-title">{item.name}</h2><p>{item.desc}</p><fieldset><legend>Choose a size</legend>{item.sizes?.map(x=><label className="choice" key={x}><input type="radio" name="size" checked={size===x} onChange={()=>setSize(x)}/><span>{x}</span></label>)}</fieldset>{['Pizza','Specialty Pizza','Strombolis'].includes(item.category)&&<fieldset><legend>Add toppings</legend><div className="choice-grid">{extras.map(x=><label className="choice" key={x}><input type="checkbox" checked={toppings.includes(x)} onChange={()=>toggle(x)}/><span>{x}</span></label>)}</div></fieldset>}<label>Special instructions<textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Allergies or preparation notes"/></label><button className="btn btn-red wide" onClick={()=>onAdd({id:crypto.randomUUID(),name:item.name,size,toppings,instructions:notes})}>ADD TO CART <Plus size={16}/></button><small>Final price and availability are confirmed by the shop.</small></div></div>}

function App(){const[selected,setSelected]=useState<MenuItem|null>(null);const[cart,setCart]=useState<CartItem[]>(()=>{try{return JSON.parse(localStorage.getItem('mama-cart')||'[]')}catch{return[]}});const update=(next:CartItem[])=>{setCart(next);localStorage.setItem('mama-cart',JSON.stringify(next))};const add=(x:CartItem)=>{update([...cart,x]);setSelected(null);window.location.href='/order'};const path=window.location.pathname.replace(/\/$/,'')||'/home';let page:React.ReactNode;switch(path){case'':case'/':case'/home':page=<Home/>;break;case'/menu':page=<MenuPage add={setSelected}/>;break;case'/our-story':page=<StoryPage/>;break;case'/locations':page=<LocationsPage/>;break;case'/contact':page=<ContactPage/>;break;case'/order':page=<OrderPage cart={cart} remove={id=>update(cart.filter(x=>x.id!==id))}/>;break;default:page=<NotFound/>}return <div className="site"><Header count={cart.length}/>{page}<Footer/>{selected&&<Customizer item={selected} onClose={()=>setSelected(null)} onAdd={add}/>}</div>}
function PreviewGate(){const[ok,setOk]=useState(sessionStorage.getItem('mama-preview-ok')==='1'),[value,setValue]=useState(''),[error,setError]=useState(false);if(ok)return <App/>;return <main className="preview-gate"><div className="preview-card"><div className="brand"><span>MAMA MIA'S</span><small>PIZZERIA · PRIVATE PREVIEW</small></div><div className="eyebrow">OWNER TEST SITE</div><h1>Welcome to the new chapter.</h1><p>This preview is private while we review the site and ordering experience.</p><form onSubmit={e=>{e.preventDefault();if(value==='mama1980'){sessionStorage.setItem('mama-preview-ok','1');setOk(true)}else setError(true)}}><label htmlFor="preview-password">Preview password</label><input id="preview-password" type="password" value={value} onChange={e=>{setValue(e.target.value);setError(false)}} autoFocus/><button className="btn btn-red">ENTER PREVIEW <ArrowRight size={16}/></button>{error&&<small className="gate-error">That password didn’t work. Try again.</small>}</form></div></main>}
createRoot(document.getElementById('root')!).render(<PreviewGate/>);
