import React, {useEffect, useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {ArrowRight, Check, Clock3, MapPin, Menu as MenuIcon, Phone, Search, X} from 'lucide-react';
import './styles.css';

type Day = {day:string; open?:string; close?:string};
export const restaurantConfig = {
  name:"Mama Mia's Pizzeria", established:1980, timezone:'America/New_York', phone:'', orderingUrl:'',
  address:{street:'1529 W 38th St', city:'Erie', state:'PA', zip:'16508'},
  features:{dineInEnabled:false, carryoutEnabled:true, deliveryEnabled:false, onlineOrderingEnabled:false, cateringEnabled:false},
  hours:[{day:'Monday'},{day:'Tuesday'},{day:'Wednesday',open:'4 PM',close:'8 PM'},{day:'Thursday',open:'4 PM',close:'8 PM'},{day:'Friday',open:'3 PM',close:'9 PM'},{day:'Saturday',open:'3 PM',close:'9 PM'},{day:'Sunday',open:'3 PM',close:'7 PM'}] as Day[],
  menu:[
    {name:'Classic Cheese',desc:'Our signature red sauce, whole-milk mozzarella, and a crisp, golden edge.',tag:'THE ORIGINAL',image:'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&w=1000&q=85'},
    {name:'Pepperoni',desc:'Cup-and-char pepperoni, mozzarella, and that sauce you know by heart.',tag:'CUSTOMER FAVORITE',image:'https://images.unsplash.com/photo-1628840042765-356cda07504e?auto=format&fit=crop&w=1000&q=85'},
    {name:'Stromboli',desc:'Rolled, oven-baked, and packed with savory fillings. Built for sharing—or not.',tag:'OVEN BAKED',image:'https://images.unsplash.com/photo-1625398407796-82650a8c135f?auto=format&fit=crop&w=1000&q=85'}
  ]
};

function status(){const now=new Date(); const day=restaurantConfig.hours[now.getDay()?now.getDay()-1:6]; if(!day.open||!day.close)return {open:false,label:'CLOSED TODAY'}; const parse=(s:string)=>{const [n,ampm]=s.split(' ');let [h,m]=n.split(':').map(Number);if(ampm==='PM'&&h!==12)h+=12;if(ampm==='AM'&&h===12)h=0;return h*60+(m||0)};const mins=now.getHours()*60+now.getMinutes();const o=parse(day.open),c=parse(day.close);return {open:mins>=o&&mins<c,label:mins<o?`OPENS TODAY AT ${day.open}`:mins<c?`OPEN UNTIL ${day.close}`:'CLOSED NOW'}}
function order(){if(restaurantConfig.orderingUrl)window.location.href=restaurantConfig.orderingUrl; else document.getElementById('order-note')?.scrollIntoView({behavior:'smooth'});}
function App(){const [menuOpen,setMenuOpen]=useState(false), [cat,setCat]=useState('Pizza'), [search,setSearch]=useState(''); const s=status(); const items=useMemo(()=>restaurantConfig.menu.filter(x=>x.name.toLowerCase().includes(search.toLowerCase())),[search]); const route=window.location.pathname.replace(/\/$/,'')||'/home';
 return <div className={`site route-${route.slice(1).replace('our-story','story').replace('locations','location')}`}><header><a className="brand" href="/home" aria-label="Mama Mia's home"><span>MAMA MIA'S</span><small>PIZZERIA · ERIE, PA</small></a><nav className={menuOpen?'open':''}><a href="/menu" onClick={()=>setMenuOpen(false)}>Menu</a><a href="/our-story" onClick={()=>setMenuOpen(false)}>Our Story</a><a href="/locations" onClick={()=>setMenuOpen(false)}>Location</a><a href="/contact" onClick={()=>setMenuOpen(false)}>Contact</a><button className="btn btn-red nav-order" onClick={order}>ORDER ONLINE <ArrowRight size={16}/></button></nav><button className="menu-btn" aria-label="Toggle menu" onClick={()=>setMenuOpen(!menuOpen)}>{menuOpen?<X/>:<MenuIcon/>}</button></header>
 <main id="top"><section className="hero"><div className="hero-copy"><div className="eyebrow"><span className="dot"/> ERIE'S NEIGHBORHOOD PIZZA</div><h1>Pizza made the way Erie remembers it.</h1><p>Fresh dough, homemade sauce, and a whole lot of local history. Mama Mia's has been bringing people together since 1980.</p><div className="actions"><button className="btn btn-red" onClick={order}>ORDER ONLINE <ArrowRight size={17}/></button><a className="btn btn-outline" href="#menu">VIEW MENU</a></div><div className="hero-meta"><div><MapPin size={16}/><span>1529 W 38th St<br/><b>Erie, PA 16508</b></span></div><div className={s.open?'open-status':''}><Clock3 size={16}/><span><b>{s.label}</b><small>Hours vary by day</small></span></div></div></div><div className="hero-art"><div className="stamp">EST.<strong>1980</strong></div><div className="pizza"><div className="pep p1"/><div className="pep p2"/><div className="pep p3"/><div className="pep p4"/><div className="pep p5"/><div className="leaf l1">✦</div><div className="leaf l2">✦</div></div><div className="art-caption"><span>THE ERIE<br/>ORIGINAL</span><small>Made fresh. Served warm.</small></div></div></section>
 <section className="quick"><button onClick={order}><span>01</span><b>Order online</b><ArrowRight/></button><a href="#menu"><span>02</span><b>Browse menu</b><ArrowRight/></a><a href="#contact" className="disabled"><span>03</span><b>Call details</b><Phone/></a><a href="https://www.google.com/maps/search/?api=1&query=Mama+Mia%27s+Pizzeria+1529+W+38th+St+Erie+PA+16508" target="_blank"><span>04</span><b>Get directions</b><MapPin/></a></section>
 <section className="section menu-section" id="menu"><div className="section-head"><div><div className="eyebrow">WHAT'S GOOD</div><h2>Popular around here.</h2></div><a className="text-link" href="#contact">See the full menu <ArrowRight size={16}/></a></div><div className="menu-tools"><div className="cats">{['Pizza','Specialty Pizza','Wings','Strombolis','Subs','Salads','Sides','Drinks'].map(x=><button className={cat===x?'active':''} onClick={()=>setCat(x)} key={x}>{x}</button>)}</div><label className="search"><Search size={16}/><input placeholder="Search menu" value={search} onChange={e=>setSearch(e.target.value)}/></label></div><div className="food-grid">{items.map((x,i)=><article className="food-card" key={x.name}><div className="food-image"><img src={x.image} alt={`${x.name} pizza`} loading={i?'lazy':'eager'}/><span>{x.tag}</span></div><div className="food-info"><h3>{x.name}</h3><p>{x.desc}</p><a href="#order-note">Customize <ArrowRight size={14}/></a></div></article>)}</div><p className="menu-note">Menu details and pricing are being updated for the new Mama Mia's chapter. Call the shop for today's availability.</p></section>
 <section className="story section" id="story"><div className="story-image"><div className="photo-label">ERIE, PA · EST. 1980</div></div><div className="story-copy"><div className="eyebrow">A NEW CHAPTER, SAME HEART</div><h2>Serving Erie since 1980.</h2><p>For more than four decades, Mama Mia's has been part of the Erie routine: pizza on busy nights, stromboli for the table, and one more slice before heading home.</p><p>We're keeping the neighborhood spirit and making it easier to find your favorites, check the hours, and get dinner on the way.</p><a className="text-link" href="#visit">Come see us <ArrowRight size={16}/></a></div></section>
 <section className="values section"><div><div className="eyebrow">WHY MAMA MIA'S</div><h2>The good stuff is simple.</h2></div><div className="value-grid"><div><strong>01</strong><h3>Fresh dough</h3><p>Made for the day, never an afterthought.</p></div><div><strong>02</strong><h3>Homemade sauce</h3><p>The red sauce that makes a pizza feel like home.</p></div><div><strong>03</strong><h3>Erie proud</h3><p>Four decades in the neighborhood and counting.</p></div></div></section>
 <section className="visit section" id="visit"><div><div className="eyebrow">FIND US IN ERIE</div><h2>Let's make dinner easy.</h2><p>Pick up something hot at 1529 W 38th St. Current hours are listed below; online ordering is coming soon.</p><div className="address"><MapPin/><span><b>Mama Mia's Pizzeria</b><br/>1529 W 38th St<br/>Erie, PA 16508</span></div><a className="btn btn-cream" href="https://www.google.com/maps/search/?api=1&query=Mama+Mia%27s+Pizzeria+1529+W+38th+St+Erie+PA+16508" target="_blank">GET DIRECTIONS <ArrowRight size={17}/></a></div><div className="hours"><h3>Hours</h3>{restaurantConfig.hours.map(x=><div key={x.day}><span>{x.day}</span><b>{x.open?`${x.open} – ${x.close}`:'Closed'}</b></div>)}</div></section>
 <section className="order-note" id="order-note"><div><div className="eyebrow">ONE MORE THING</div><h2>What's for dinner?</h2><p>Online ordering is being connected now. For today's menu and availability, send us a note.</p></div><a className="btn btn-red" href="#contact">CONTACT THE SHOP <Phone size={17}/></a></section>
 <section className="contact section" id="contact"><div><div className="eyebrow">SAY HELLO</div><h2>Questions? We’re here.</h2><p>Send a note and we’ll get back to you. For orders, please call the shop.</p></div><form onSubmit={e=>{e.preventDefault();alert('Thanks! Your message is ready to send once email delivery is connected.')}}><input aria-label="Name" placeholder="Your name" required/><input aria-label="Email" type="email" placeholder="Email address" required/><textarea aria-label="Message" placeholder="How can we help?" required/><button className="btn btn-dark">SEND MESSAGE <Check size={16}/></button></form></section></main>
 <footer><div className="brand"><span>MAMA MIA'S</span><small>PIZZERIA · ERIE, PA</small></div><div><b>1529 W 38th St · Erie, PA 16508</b><span>Serving Erie since 1980.</span></div><div className="social">Instagram · Facebook</div></footer><div className="mobile-bar"><a href="#menu">MENU</a><button onClick={order}>ORDER ONLINE</button><a href="https://www.google.com/maps/search/?api=1&query=Mama+Mia%27s+Pizzeria+1529+W+38th+St+Erie+PA+16508">DIRECTIONS</a></div></div>}
createRoot(document.getElementById('root')!).render(<App/>);
